import { query } from './db';

/**
 * Theme Renderer - Fetches theme data from database and generates CSS
 * This replaces the hardcoded theme with a database-driven system
 */

export async function getThemeCSS(themeId = 1, pageId = null) {
  try {
    // Fetch page theme overrides if pageId is provided
    let pageOverrides = null;
    if (pageId) {
      const overrideResults = await query(
        `SELECT override_config FROM page_theme_overrides WHERE page_id = ? AND is_active = 1`,
        [pageId]
      );
      if (overrideResults.length > 0) {
        pageOverrides = JSON.parse(overrideResults[0].override_config);
      }
    }

    // Fetch all theme settings
    const settings = await query(
      `SELECT * FROM theme_settings WHERE theme_id = ?`,
      [themeId]
    );

    // Apply page overrides to settings
    const mergedSettings = mergeOverrides(settings, pageOverrides?.colors, 'key');

    // Fetch typography
    const typography = await query(
      `SELECT * FROM theme_typography WHERE theme_id = ?`,
      [themeId]
    );

    // Apply page overrides to typography
    const mergedTypography = mergeOverrides(typography, pageOverrides?.typography, 'id');

    // Fetch breakpoints
    const breakpoints = await query(
      `SELECT * FROM theme_breakpoints WHERE theme_id = ?`,
      [themeId]
    );

    // Apply page overrides to spacing (from settings)
    const mergedSpacing = mergeOverrides(
      settings.filter(s => s.category === 'spacing'),
      pageOverrides?.spacing,
      'key'
    );

    // Fetch animations
    const animations = await query(
      `SELECT * FROM theme_animations WHERE theme_id = ? AND is_enabled = 1`,
      [themeId]
    );

    // Fetch components
    const components = await query(
      `SELECT * FROM theme_components WHERE theme_id = ? AND is_visible = 1`,
      [themeId]
    );

    // Fetch sections
    const sections = await query(
      `SELECT * FROM theme_sections WHERE theme_id = ? AND is_visible = 1`,
      [themeId]
    );

    // Apply page overrides to sections
    const mergedSections = mergeOverrides(sections, pageOverrides?.sections, 'section_id');

    // Fetch SVG icons
    const svgIcons = await query(
      `SELECT * FROM theme_svg_icons WHERE theme_id = ?`,
      [themeId]
    );

    // Generate CSS
    const css = generateThemeCSS({
      settings: mergedSettings,
      typography: mergedTypography,
      breakpoints,
      animations,
      components,
      sections: mergedSections,
      svgIcons
    });

    return css;
  } catch (error) {
    console.error('Error generating theme CSS:', error);
    return generateDefaultCSS();
  }
}

function mergeOverrides(globalData, overrides, keyField) {
  if (!overrides || Object.keys(overrides).length === 0) {
    return globalData;
  }

  return globalData.map(item => {
    const overrideKey = item[keyField];
    if (overrides[overrideKey]) {
      return { ...item, ...overrides[overrideKey] };
    }
    return item;
  });
}

function generateThemeCSS(data) {
  let css = '/* Generated by Theme Renderer */\n';
  css += ':root {\n';

  // Add CSS variables from settings
  data.settings.forEach(setting => {
    css += `  ${setting.key}: ${setting.value};\n`;
  });

  css += '}\n\n';

  // Add typography
  if (data.typography && data.typography.length > 0) {
    css += '/* Typography */\n';
    data.typography.forEach(font => {
      css += `${font.css_variable} {\n`;
      css += `  font-family: ${font.font_family};\n`;
      if (font.font_weight) css += `  font-weight: ${font.font_weight};\n`;
      if (font.font_size) css += `  font-size: ${font.font_size};\n`;
      if (font.line_height) css += `  line-height: ${font.line_height};\n`;
      if (font.letter_spacing) css += `  letter-spacing: ${font.letter_spacing};\n`;
      if (font.text_transform) css += `  text-transform: ${font.text_transform};\n`;
      css += '}\n\n';
    });
  }

  // Add responsive breakpoints
  if (data.breakpoints && data.breakpoints.length > 0) {
    css += '/* Responsive Breakpoints */\n';
    data.breakpoints.forEach(bp => {
      if (bp.max_width) {
        css += `@media (max-width: ${bp.max_width}px) {\n`;
        if (bp.container_max_width) {
          css += `  .container { max-width: ${bp.container_max_width}; }\n`;
        }
        if (bp.container_padding) {
          css += `  .container { padding: 0 ${bp.container_padding}; }\n`;
        }
        if (bp.custom_css) {
          css += `  ${bp.custom_css}\n`;
        }
        css += '}\n\n';
      }
      if (bp.min_width) {
        css += `@media (min-width: ${bp.min_width}px) {\n`;
        if (bp.container_max_width) {
          css += `  .container { max-width: ${bp.container_max_width}; }\n`;
        }
        if (bp.container_padding) {
          css += `  .container { padding: 0 ${bp.container_padding}; }\n`;
        }
        if (bp.custom_css) {
          css += `  ${bp.custom_css}\n`;
        }
        css += '}\n\n';
      }
    });
  }

  // Add animations
  if (data.animations && data.animations.length > 0) {
    css += '/* Animations */\n';
    data.animations.forEach(anim => {
      css += `@keyframes ${anim.animation_name} {\n`;
      css += `  ${anim.keyframes}\n`;
      css += '}\n\n';
      
      css += `.${anim.css_class} {\n`;
      css += `  animation: ${anim.animation_name} ${anim.duration} ${anim.timing_function} ${anim.delay} ${anim.iteration_count} ${anim.direction} ${anim.fill_mode} ${anim.play_state};\n`;
      css += '}\n\n';
    });
  }

  // Add component styles
  if (data.components && data.components.length > 0) {
    css += '/* Component Styles */\n';
    data.components.forEach(comp => {
      css += `/* ${comp.component_name} */\n`;
      if (comp.styles) {
        try {
          const styles = typeof comp.styles === 'string' ? JSON.parse(comp.styles) : comp.styles;
          css += `.${comp.css_class} {\n`;
          Object.entries(styles).forEach(([prop, value]) => {
            css += `  ${prop}: ${value};\n`;
          });
          css += '}\n\n';
        } catch (e) {
          css += `.${comp.css_class} {\n  ${comp.styles}\n}\n\n`;
        }
      }
    });
  }

  // Add section styles
  if (data.sections && data.sections.length > 0) {
    css += '/* Section Styles */\n';
    data.sections.forEach(section => {
      css += `/* ${section.section_name} */\n`;
      if (section.section_id) {
        css += `#${section.section_id}, .${section.section_id} {\n`;
        
        if (section.background_type === 'color' && section.background_value) {
          css += `  background-color: ${section.background_value};\n`;
        } else if (section.background_type === 'gradient' && section.background_value) {
          css += `  background: ${section.background_value};\n`;
        } else if (section.background_type === 'image' && section.background_value) {
          css += `  background-image: url('${section.background_value}');\n`;
          css += `  background-size: cover;\n`;
          css += `  background-position: center;\n`;
        }
        
        if (section.background_overlay) {
          css += `  background-overlay: ${section.background_overlay};\n`;
        }
        
        if (section.padding_top) {
          css += `  padding-top: ${section.padding_top};\n`;
        }
        
        if (section.padding_bottom) {
          css += `  padding-bottom: ${section.padding_bottom};\n`;
        }
        
        if (section.text_color) {
          css += `  color: ${section.text_color};\n`;
        }
        
        if (section.custom_css) {
          css += `  ${section.custom_css}\n`;
        }
        
        css += '}\n\n';
      }
    });
  }

  // Add SVG icon overrides
  if (data.svgIcons && data.svgIcons.length > 0) {
    css += '/* SVG Icon Styles */\n';
    data.svgIcons.forEach(icon => {
      css += `.${icon.icon_class} {\n`;
      if (icon.custom_fill) {
        css += `  fill: ${icon.custom_fill};\n`;
      } else if (icon.fill_rule === 'currentColor') {
        css += `  fill: currentColor;\n`;
      } else if (icon.fill_rule === 'none') {
        css += `  fill: none;\n`;
      }
      
      if (icon.custom_stroke) {
        css += `  stroke: ${icon.custom_stroke};\n`;
      } else if (icon.stroke_rule === 'currentColor') {
        css += `  stroke: currentColor;\n`;
      } else if (icon.stroke_rule === 'none') {
        css += `  stroke: none;\n`;
      }
      
      if (icon.stroke_width) {
        css += `  stroke-width: ${icon.stroke_width};\n`;
      }
      css += '}\n\n';
    });
  }

  return css;
}

function generateDefaultCSS() {
  return `/* Default Theme Fallback */
:root {
  --navy-950: #0A1628;
  --navy-900: #0F1F3D;
  --navy-850: #122647;
  --orange: #FF6B1A;
  --orange-dim: #c9540f;
  --green: #12B76A;
  --green-dim: #0C8A50;
  --yellow: #FFC93C;
  --cyan: #00D4FF;
  --blue: #3B82F6;
  --purple: #A855F7;
  --white: #FFFFFF;
  --gray-100: #F4F6F9;
  --gray-200: #E7EBF1;
  --graphite-800: #1E2530;
  --graphite-500: #5B6472;
  --font-display: 'Space Grotesk', sans-serif;
  --font-body: 'Inter', sans-serif;
  --font-mono: 'IBM Plex Mono', monospace;
  --section-pad: 9rem;
}`;
}

export async function getThemeData(themeId = 1) {
  try {
    const theme = await query(
      `SELECT * FROM themes WHERE id = ?`,
      [themeId]
    );

    const settings = await query(
      `SELECT * FROM theme_settings WHERE theme_id = ?`,
      [themeId]
    );

    const typography = await query(
      `SELECT * FROM theme_typography WHERE theme_id = ?`,
      [themeId]
    );

    const breakpoints = await query(
      `SELECT * FROM theme_breakpoints WHERE theme_id = ?`,
      [themeId]
    );

    return {
      theme: theme[0],
      settings,
      typography,
      breakpoints
    };
  } catch (error) {
    console.error('Error fetching theme data:', error);
    return null;
  }
}

export async function getActiveThemeId() {
  try {
    const result = await query(
      `SELECT id FROM themes WHERE is_active = 1 AND is_default = 1 LIMIT 1`
    );
    return result[0]?.id || 1;
  } catch (error) {
    console.error('Error fetching active theme ID:', error);
    return 1;
  }
}
